/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact { 'name' : string, 'phoneNumber' : string }
export interface Settings { 'emergencyNumber' : string }
export interface _SERVICE {
  'addContact' : ActorMethod<[string, string], bigint>,
  'deleteContact' : ActorMethod<[bigint], undefined>,
  'editContact' : ActorMethod<[bigint, string, string], undefined>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getContact' : ActorMethod<[bigint], Contact>,
  'getSettings' : ActorMethod<[], Settings>,
  'updateSettings' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];