/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const Settings = IDL.Record({ 'emergencyNumber' : IDL.Text });

export const idlService = IDL.Service({
  'addContact' : IDL.Func([IDL.Text, IDL.Text], [IDL.Int], []),
  'deleteContact' : IDL.Func([IDL.Int], [], []),
  'editContact' : IDL.Func([IDL.Int, IDL.Text, IDL.Text], [], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getContact' : IDL.Func([IDL.Int], [Contact], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'updateSettings' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({ 'name' : IDL.Text, 'phoneNumber' : IDL.Text });
  const Settings = IDL.Record({ 'emergencyNumber' : IDL.Text });
  
  return IDL.Service({
    'addContact' : IDL.Func([IDL.Text, IDL.Text], [IDL.Int], []),
    'deleteContact' : IDL.Func([IDL.Int], [], []),
    'editContact' : IDL.Func([IDL.Int, IDL.Text, IDL.Text], [], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getContact' : IDL.Func([IDL.Int], [Contact], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'updateSettings' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };